begin;

insert into sport values(1, 'Basketball') on conflict do nothing;
insert into sport values(2, 'Football') on conflict do nothing;

insert into league values('NBA', 'NBA', 1) on conflict do nothing;
insert into league values('NFL', 'NFL', 2) on conflict do nothing;

insert into club values(1,1,'Atlanta','Hawks') on conflict do nothing;
insert into club values(2,1,'Boston','Celtics') on conflict do nothing;
insert into club values(3,1,'New Jersey','Nets') on conflict do nothing;
insert into club values(3,2,'Brooklyn','Nets') on conflict do nothing;
insert into club values(4,1,'Charlotte','Bobcats') on conflict do nothing;
insert into club values(4,2,'Charlotte','Hornets') on conflict do nothing;
insert into club values(5,1,'Chicago','Bulls') on conflict do nothing;
insert into club values(6,1,'Cleveland','Cavaliers') on conflict do nothing;
insert into club values(7,1,'Dallas','Mavericks') on conflict do nothing;
insert into club values(8,1,'Denver','Nuggets') on conflict do nothing;
insert into club values(9,1,'Detroit','Pistons') on conflict do nothing;
insert into club values(10,1,'Golden State','Warriors') on conflict do nothing;
insert into club values(11,1,'Houston','Rockets') on conflict do nothing;
insert into club values(12,1,'Indiana','Pacers') on conflict do nothing;
insert into club values(13,1,'Los Angeles','Clippers') on conflict do nothing;
insert into club values(14,1,'Los Angeles','Lakers') on conflict do nothing;
insert into club values(15,1,'Memphis','Grizzlies') on conflict do nothing;
insert into club values(16,1,'Miami','Heat') on conflict do nothing;
insert into club values(17,1,'Milwaukee','Bucks') on conflict do nothing;
insert into club values(18,1,'Minnesota','Timberwolves') on conflict do nothing;
insert into club values(19,1,'New Orleans','Hornets') on conflict do nothing;
insert into club values(19,2,'New Orleans','Pelicans') on conflict do nothing;
insert into club values(20,1,'New York','Knicks') on conflict do nothing;
insert into club values(21,1,'Oklahoma City','Thunder') on conflict do nothing;
insert into club values(22,1,'Orlando','Magic') on conflict do nothing;
insert into club values(23,1,'Philadelphia','76ers') on conflict do nothing;
insert into club values(24,1,'Phoenix','Suns') on conflict do nothing;
insert into club values(25,1,'Portland','Trail Blazers') on conflict do nothing;
insert into club values(26,1,'Sacramento','Kings') on conflict do nothing;
insert into club values(27,1,'San Antonio','Spurs') on conflict do nothing;
insert into club values(28,1,'Toronto','Raptors') on conflict do nothing;
insert into club values(29,1,'Utah','Jazz') on conflict do nothing;
insert into club values(30,1,'Washington','Wizards') on conflict do nothing;
insert into club values(31,1,'Arizona','Cardinals') on conflict do nothing;
insert into club values(32,1,'Atlanta','Falcons') on conflict do nothing;
insert into club values(33,1,'Baltimore','Ravens') on conflict do nothing;
insert into club values(34,1,'Buffalo','Bills') on conflict do nothing;
insert into club values(35,1,'Carolina','Panthers') on conflict do nothing;
insert into club values(36,1,'Chicago','Bears') on conflict do nothing;
insert into club values(37,1,'Cincinnati','Bengals') on conflict do nothing;
insert into club values(38,1,'Cleveland','Browns') on conflict do nothing;
insert into club values(39,1,'Dallas','Cowboys') on conflict do nothing;
insert into club values(40,1,'Denver','Broncos') on conflict do nothing;
insert into club values(41,1,'Detroit','Lions') on conflict do nothing;
insert into club values(42,1,'Green Bay','Packers') on conflict do nothing;
insert into club values(43,1,'Houston','Texans') on conflict do nothing;
insert into club values(44,1,'Indianapolis','Colts') on conflict do nothing;
insert into club values(45,1,'Jacksonville','Jaguars') on conflict do nothing;
insert into club values(46,1,'Kansas City','Chiefs') on conflict do nothing;
insert into club values(47,1,'Oakland','Raiders') on conflict do nothing;
insert into club values(47,2,'Las Vegas','Raiders') on conflict do nothing;
insert into club values(48,1,'San Diego','Chargers') on conflict do nothing;
insert into club values(48,2,'Los Angeles','Chargers') on conflict do nothing;
insert into club values(49,2,'Los Angeles','Rams') on conflict do nothing;
insert into club values(49,1,'St. Louis','Rams') on conflict do nothing;
insert into club values(50,1,'Miami','Dolphins') on conflict do nothing;
insert into club values(51,1,'Minnesota','Vikings') on conflict do nothing;
insert into club values(52,1,'New England','Patriots') on conflict do nothing;
insert into club values(53,1,'New Orleans','Saints') on conflict do nothing;
insert into club values(54,1,'New York','Giants') on conflict do nothing;
insert into club values(55,1,'New York','Jets') on conflict do nothing;
insert into club values(56,1,'Philadelphia','Eagles') on conflict do nothing;
insert into club values(57,1,'Pittsburgh','Steelers') on conflict do nothing;
insert into club values(58,1,'San Francisco','49ers') on conflict do nothing;
insert into club values(59,1,'Seattle','Seahawks') on conflict do nothing;
insert into club values(60,1,'Tampa Bay','Buccaneers') on conflict do nothing;
insert into club values(61,1,'Tennessee','Titans') on conflict do nothing;
insert into club values(62,1,'Washington','Redskins') on conflict do nothing;

commit;
